[build]
  functions = "functions"
  node_bundler = "esbuild"

[functions."api"]
  memory = 1024
  timeout = 40  # Increased timeout to 40 seconds
  node_bundler = "esbuild"
  external_node_modules = ["chrome-aws-lambda"]
